image: node:14

include:
  - template: Dependency-Scanning.gitlab-ci.yml
  - project: 'devmint/gitlab-templates'
    file: '/publish-npm-package.yml'

variables:
  PROJECT_ID: 18816882

stages:
  - test
  - build
  - publish

cache:
  paths:
    - node_modules/

eslint code:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run lint

unit tests:
  stage: test
  before_script:
    - npm ci
  script:
    - npm run test

outdated dependencies:
  stage: test
  before_script:
    - npm ci
  script:
    - npm audit

build package:
  stage: build
  before_script:
    - npm ci
  script:
    - npm run build
  artifacts:
    paths:
      - dist/