name: Test & Tag

on:
  push:
    branches: [ master ]
  pull_request: 
    branches: [ master ]

jobs:
  CodeQuality:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - run: npm run lint
  UnitTesting:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - uses: bahmutov/npm-install@v1
      - uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run test:coverage"
          coverage-comment: ${{ github.ref != 'refs/heads/master' }}
  TagPackage:
    runs-on: ubuntu-latest
    needs: [ CodeQuality, UnitTesting ]
    if: github.ref == 'refs/heads/master'
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
      - uses: pkgdeps/action-package-version-to-git-tag@v1
        with:
          github_token: ${{ secrets.PAT }}
          github_repo: ${{ github.repository }}
          git_commit_sha: ${{ github.sha }}
          git_tag_prefix: "v"